--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      UNAM
-- Project :      Proyecto_Air.DM1
-- Author :       Arturo
--
-- Date Created : Thursday, May 23, 2024 20:43:28
-- Target DBMS : Oracle 11g
--

-- 
-- TABLE: AERONAVE 
--

CREATE TABLE AERONAVE(
    AERONAVE_ID         NUMBER(10, 0)    NOT NULL,
    MODELO              VARCHAR2(50)     NOT NULL,
    MATRICULA           VARCHAR2(10)     NOT NULL,
    ESPECIFICACIONES    BLOB             NOT NULL,
    ES_COMERICAL        NUMBER(1, 0)     NOT NULL,
    ES_CARGA            NUMBER(1, 0)     NOT NULL,
    CONSTRAINT PK1 PRIMARY KEY (AERONAVE_ID)
)
;



-- 
-- TABLE: AERONAVE_CARGA 
--

CREATE TABLE AERONAVE_CARGA(
    AERONAVE_ID                NUMBER(10, 0)    NOT NULL,
    BODEGAS                    NUMBER(5, 0)     NOT NULL,
    CAPACIDAD_CARGA            NUMBER(5, 0)     NOT NULL,
    ALTO                       NUMBER(7, 2)     NOT NULL,
    ANCHO                      NUMBER(7, 2),
    PROFUNDIDAD                NUMBER(7, 2),
    AEROPUERTO_RESGUARDO_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK3 PRIMARY KEY (AERONAVE_ID), 
    CONSTRAINT RefAERONAVE2 FOREIGN KEY (AERONAVE_ID)
    REFERENCES AERONAVE(AERONAVE_ID),
    CONSTRAINT RefAEROPUERTO23 FOREIGN KEY (AEROPUERTO_RESGUARDO_ID)
    REFERENCES AEROPUERTO(AEROPUERTO_ID)
)
;



-- 
-- TABLE: AERONAVE_COMERCIAL 
--

CREATE TABLE AERONAVE_COMERCIAL(
    AERONAVE_ID                 NUMBER(10, 0)    NOT NULL,
    CAPACIDAD_ORDINARIOS        NUMBER(4, 0)     NOT NULL,
    CAPACIDAD_VIP               NUMBER(4, 0)     NOT NULL,
    CAPACIDAD_DISCAPACITADOS    NUMBER(4, 0)     NOT NULL,
    CONSTRAINT PK2 PRIMARY KEY (AERONAVE_ID), 
    CONSTRAINT RefAERONAVE1 FOREIGN KEY (AERONAVE_ID)
    REFERENCES AERONAVE(AERONAVE_ID)
)
;



-- 
-- TABLE: AEROPUERTO 
--

CREATE TABLE AEROPUERTO(
    AEROPUERTO_ID    NUMBER(10, 0)    NOT NULL,
    CLAVE            VARCHAR2(13)     NOT NULL,
    NOMBRE           VARCHAR2(40)     NOT NULL,
    LATITUD          VARCHAR2(50)     NOT NULL,
    LONGITUD         VARCHAR2(50)     NOT NULL,
    ESTA_ACTIVO      CHAR(1)          NOT NULL,
    CONSTRAINT PK6 PRIMARY KEY (AEROPUERTO_ID)
)
;



-- 
-- TABLE: EMPLEADO 
--

CREATE TABLE EMPLEADO(
    EMPLEADO_ID      NUMBER(10, 0)    NOT NULL,
    NOMBRE           VARCHAR2(40)     NOT NULL,
    AP_PAT           VARCHAR2(40)     NOT NULL,
    AP_MAT           VARCHAR2(40),
    RFC              VARCHAR2(13)     NOT NULL,
    CURP             VARCHAR2(18)     NOT NULL,
    FOTO             BLOB             NOT NULL,
    JEFE_EMPLEADO    NUMBER(10, 0),
    PUESTO_ID        VARCHAR2(40)     NOT NULL,
    CONSTRAINT PK7 PRIMARY KEY (EMPLEADO_ID), 
    CONSTRAINT RefPUESTO13 FOREIGN KEY (PUESTO_ID)
    REFERENCES PUESTO(PUESTO_ID),
    CONSTRAINT RefEMPLEADO14 FOREIGN KEY (JEFE_EMPLEADO)
    REFERENCES EMPLEADO(EMPLEADO_ID)
)
;



-- 
-- TABLE: EMPLEADO_VUELO 
--

CREATE TABLE EMPLEADO_VUELO(
    EMPLEADO_ID        NUMBER(10, 0)    NOT NULL,
    VUELO_ID           NUMBER(10, 0)    NOT NULL,
    PUNTUACION         VARCHAR2(40),
    ROL_EMPLEADO_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK19 PRIMARY KEY (EMPLEADO_ID, VUELO_ID), 
    CONSTRAINT RefEMPLEADO26 FOREIGN KEY (EMPLEADO_ID)
    REFERENCES EMPLEADO(EMPLEADO_ID),
    CONSTRAINT RefVUELO27 FOREIGN KEY (VUELO_ID)
    REFERENCES VUELO(VUELO_ID),
    CONSTRAINT RefROL_EMPLEADO28 FOREIGN KEY (ROL_EMPLEADO_ID)
    REFERENCES ROL_EMPLEADO(ROL_EMPLEADO_ID)
)
;



-- 
-- TABLE: EQUIPAJE 
--

CREATE TABLE EQUIPAJE(
    NUM_EQUIPAJE    VARCHAR2(40)     NOT NULL,
    PASE_ID         NUMBER(10, 0)    NOT NULL,
    PESO_KG         NUMBER(4, 0),
    CONSTRAINT PK14 PRIMARY KEY (NUM_EQUIPAJE, PASE_ID), 
    CONSTRAINT RefPASE16 FOREIGN KEY (PASE_ID)
    REFERENCES PASE(PASE_ID)
)
;



-- 
-- TABLE: HISTORICO_STATUS_VUELO 
--

CREATE TABLE HISTORICO_STATUS_VUELO(
    HISTORICO_STATUS_VUELO_ID    VARCHAR2(40)     NOT NULL,
    FECHA_STATUS                 DATE             NOT NULL,
    VUELO_ID                     NUMBER(10, 0)    NOT NULL,
    STATUS_VUELO_ID              VARCHAR2(40)     NOT NULL,
    CONSTRAINT PK15 PRIMARY KEY (HISTORICO_STATUS_VUELO_ID), 
    CONSTRAINT RefVUELO19 FOREIGN KEY (VUELO_ID)
    REFERENCES VUELO(VUELO_ID),
    CONSTRAINT RefSTATUS_VUELO20 FOREIGN KEY (STATUS_VUELO_ID)
    REFERENCES STATUS_VUELO(STATUS_VUELO_ID)
)
;



-- 
-- TABLE: PAQUETE 
--

CREATE TABLE PAQUETE(
    PAQUETE_ID         VARCHAR2(40)     NOT NULL,
    FOLIO              VARCHAR2(18)     NOT NULL,
    PESO               NUMBER(7, 0)     NOT NULL,
    TIPO_PAQUETE_ID    VARCHAR2(40)     NOT NULL,
    VUELO_ID           NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK12 PRIMARY KEY (PAQUETE_ID), 
    CONSTRAINT RefTIPO_PAQUETE15 FOREIGN KEY (TIPO_PAQUETE_ID)
    REFERENCES TIPO_PAQUETE(TIPO_PAQUETE_ID),
    CONSTRAINT RefVUELO32 FOREIGN KEY (VUELO_ID)
    REFERENCES VUELO(VUELO_ID)
)
;



-- 
-- TABLE: PASAJERO 
--

CREATE TABLE PASAJERO(
    PASAJERO_ID         VARCHAR2(40)    NOT NULL,
    NOMBRE              VARCHAR2(40)    NOT NULL,
    AP_PAT              VARCHAR2(40)    NOT NULL,
    AP_MAT              VARCHAR2(40),
    EMAIL               VARCHAR2(40)    NOT NULL,
    FECHA_NACIMIENTO    DATE            NOT NULL,
    CURP                VARCHAR2(18)    NOT NULL,
    CONSTRAINT PK4 PRIMARY KEY (PASAJERO_ID)
)
;



-- 
-- TABLE: PASAJERO_VUELO 
--

CREATE TABLE PASAJERO_VUELO(
    PASAJERO_VUELO_ID    NUMBER(10, 0)     NOT NULL,
    ATENCION_ESPECIAL    VARCHAR2(2000),
    PRESENTE             NUMBER(1, 0),
    NUM_ASIENTO          NUMBER(3, 0),
    VUELO_ID             NUMBER(10, 0)     NOT NULL,
    PASAJERO_ID          VARCHAR2(40)      NOT NULL,
    CONSTRAINT PK21 PRIMARY KEY (PASAJERO_VUELO_ID), 
    CONSTRAINT RefVUELO29 FOREIGN KEY (VUELO_ID)
    REFERENCES VUELO(VUELO_ID),
    CONSTRAINT RefPASAJERO30 FOREIGN KEY (PASAJERO_ID)
    REFERENCES PASAJERO(PASAJERO_ID)
)
;



-- 
-- TABLE: PASE 
--

CREATE TABLE PASE(
    PASE_ID              NUMBER(10, 0)    NOT NULL,
    FOLIO_ID             VARCHAR2(8)      NOT NULL,
    FECHA_IMPRESION      TIMESTAMP(6)     NOT NULL,
    PASAJERO_VUELO_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK11 PRIMARY KEY (PASE_ID), 
    CONSTRAINT RefPASAJERO_VUELO31 FOREIGN KEY (PASAJERO_VUELO_ID)
    REFERENCES PASAJERO_VUELO(PASAJERO_VUELO_ID)
)
;



-- 
-- TABLE: PUESTO 
--

CREATE TABLE PUESTO(
    PUESTO_ID         VARCHAR2(40)    NOT NULL,
    NOMBRE_CARGO      VARCHAR2(40)    NOT NULL,
    DESCRIPCION       VARCHAR2(50)    NOT NULL,
    SUELDO_MENSUAL    VARCHAR2(40)    NOT NULL,
    CLAVE_PUESTO      VARCHAR2(4)     NOT NULL,
    CONSTRAINT PK9 PRIMARY KEY (PUESTO_ID)
)
;



-- 
-- TABLE: ROL_EMPLEADO 
--

CREATE TABLE ROL_EMPLEADO(
    ROL_EMPLEADO_ID    NUMBER(10, 0)    NOT NULL,
    DESCRIPCION        VARCHAR2(40)     NOT NULL,
    NOMBRE             VARCHAR2(40)     NOT NULL,
    CONSTRAINT PK20 PRIMARY KEY (ROL_EMPLEADO_ID)
)
;



-- 
-- TABLE: STATUS_VUELO 
--

CREATE TABLE STATUS_VUELO(
    STATUS_VUELO_ID    VARCHAR2(40)     NOT NULL,
    CLAVE              VARCHAR2(40)     NOT NULL,
    DESCRIPCION        VARCHAR2(400)    NOT NULL,
    ACTIVO             NUMBER(1, 0)     NOT NULL,
    CONSTRAINT PK16 PRIMARY KEY (STATUS_VUELO_ID)
)
;



-- 
-- TABLE: TIPO_PAQUETE 
--

CREATE TABLE TIPO_PAQUETE(
    TIPO_PAQUETE_ID        VARCHAR2(40)     NOT NULL,
    CLAVE                  NUMBER(10, 0)    NOT NULL,
    DESCRIPCION            VARCHAR2(400)    NOT NULL,
    INDICACIONES_MANEJ0    VARCHAR2(500),
    CONSTRAINT PK13 PRIMARY KEY (TIPO_PAQUETE_ID)
)
;



-- 
-- TABLE: UBICACION_MONITOREO 
--

CREATE TABLE UBICACION_MONITOREO(
    NUM_MEDICION    NUMBER(10, 0)    NOT NULL,
    VUELO_ID        NUMBER(10, 0)    NOT NULL,
    LATITUD         NUMBER(5, 2)     NOT NULL,
    LONGITUD        NUMBER(5, 2)     NOT NULL,
    FECHA_EXACTA    DATE,
    CONSTRAINT PK22 PRIMARY KEY (NUM_MEDICION, VUELO_ID), 
    CONSTRAINT RefVUELO33 FOREIGN KEY (VUELO_ID)
    REFERENCES VUELO(VUELO_ID)
)
;



-- 
-- TABLE: VUELO 
--

CREATE TABLE VUELO(
    VUELO_ID              NUMBER(10, 0)    NOT NULL,
    NUM_VUELO             NUMBER(5, 0)     NOT NULL,
    FECHA_SALIDA          TIMESTAMP(6)     NOT NULL,
    FECHA_LLEGADA         TIMESTAMP(6)     NOT NULL,
    SALA                  NUMBER(3, 0),
    FECHA_STATUS          DATE             NOT NULL,
    AEROPUERTO_ORIGEN     NUMBER(10, 0)    NOT NULL,
    AEROPUERTO_DESTINO    NUMBER(10, 0)    NOT NULL,
    STATUS_VUELO_ID       VARCHAR2(40)     NOT NULL,
    AERONAVE_ID           NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK5 PRIMARY KEY (VUELO_ID), 
    CONSTRAINT RefAEROPUERTO5 FOREIGN KEY (AEROPUERTO_ORIGEN)
    REFERENCES AEROPUERTO(AEROPUERTO_ID),
    CONSTRAINT RefAEROPUERTO7 FOREIGN KEY (AEROPUERTO_DESTINO)
    REFERENCES AEROPUERTO(AEROPUERTO_ID),
    CONSTRAINT RefSTATUS_VUELO22 FOREIGN KEY (STATUS_VUELO_ID)
    REFERENCES STATUS_VUELO(STATUS_VUELO_ID),
    CONSTRAINT RefAERONAVE24 FOREIGN KEY (AERONAVE_ID)
    REFERENCES AERONAVE(AERONAVE_ID)
)
;



-- 
-- TABLE: WEB_EMPLEADO 
--

CREATE TABLE WEB_EMPLEADO(
    WEB_EMPLEADO_ID    NUMBER(10, 0)    NOT NULL,
    URL_EMPLEADO       VARCHAR2(300)    NOT NULL,
    EMPLEADO_ID        NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK18 PRIMARY KEY (WEB_EMPLEADO_ID), 
    CONSTRAINT RefEMPLEADO34 FOREIGN KEY (EMPLEADO_ID)
    REFERENCES EMPLEADO(EMPLEADO_ID)
)
;



