--@Autor(es): Francisco Hernandez Arturo
--            Toldedo Valencia Jesus Antonio   
--@Fecha creación: 01/06/2024
--@Descripción: Creación de usuarios y roles

-- TABLE: PUESTO 

CREATE TABLE PUESTO(
    PUESTO_ID         NUMBER(10, 0)    NOT NULL,
    NOMBRE_CARGO      VARCHAR2(40)    NOT NULL,
    DESCRIPCION       VARCHAR2(50)    NOT NULL,
    SUELDO_MENSUAL    VARCHAR2(40)    NOT NULL,
    CLAVE_PUESTO      VARCHAR2(4)     NOT NULL,
    CONSTRAINT PUESTO_PK PRIMARY KEY (PUESTO_ID),
    CONSTRAINT PUESTO_CLAVE_PUESTO_CHK CHECK (CLAVE_PUESTO IN ('PILO','COPI','JSOB', 'ASOB'))
);

-- TABLE: ROL_EMPLEADO 

CREATE TABLE ROL_EMPLEADO(
    ROL_EMPLEADO_ID    NUMBER(10, 0)    NOT NULL,
    DESCRIPCION        VARCHAR2(40)     NOT NULL,
    NOMBRE             VARCHAR2(40)     NOT NULL,
    CONSTRAINT ROL_EMPLEADO_PK PRIMARY KEY (ROL_EMPLEADO_ID)
);

-- TABLE: PASAJERO 

--Valida curp con trigger tentativamente
CREATE TABLE PASAJERO(
    PASAJERO_ID         NUMBER(10,0)    NOT NULL,
    NOMBRE              VARCHAR2(40)    NOT NULL,
    AP_PAT              VARCHAR2(40)    NOT NULL,
    AP_MAT              VARCHAR2(40),
    EMAIL               VARCHAR2(40)    NOT NULL,
    FECHA_NACIMIENTO    DATE            NOT NULL,
    CURP                VARCHAR2(18)    NOT NULL,
    CONSTRAINT PASAJERO_PK PRIMARY KEY (PASAJERO_ID),
    CONSTRAINT PASAJERO_EMAIL_UK UNIQUE (EMAIL),
    CONSTRAINT PASAJERO_CURP_UK UNIQUE (CURP)
);

-- TABLE: STATUS_VUELO 

CREATE TABLE STATUS_VUELO(
    STATUS_VUELO_ID    NUMBER(10, 0)     NOT NULL,
    CLAVE              VARCHAR2(40)     NOT NULL,
    DESCRIPCION        VARCHAR2(400)    NOT NULL,
    ACTIVO             NUMBER(1, 0)     NOT NULL,
    CONSTRAINT STATUS_VUELO_PK PRIMARY KEY (STATUS_VUELO_ID)
);


-- TABLE: TIPO_PAQUETE 

CREATE TABLE TIPO_PAQUETE(
    TIPO_PAQUETE_ID        NUMBER(10, 0)    NOT NULL,
    CLAVE                  NUMBER(10, 0)    NOT NULL,
    DESCRIPCION            VARCHAR2(400)    NOT NULL,
    INDICACIONES_MANEJ0    VARCHAR2(500),
    CONSTRAINT TIPO_PAQUETE_PK PRIMARY KEY (TIPO_PAQUETE_ID)
);

-- TABLE: AEROPUERTO 

CREATE TABLE AEROPUERTO(
    AEROPUERTO_ID    NUMBER(10, 0)    NOT NULL,
    CLAVE            VARCHAR2(13)     NOT NULL,
    NOMBRE           VARCHAR2(40)     NOT NULL,
    LATITUD          VARCHAR2(50)     NOT NULL,
    LONGITUD         VARCHAR2(50)     NOT NULL,
    ESTA_ACTIVO      CHAR(1)          NOT NULL,
    CONSTRAINT AEROPUERTO_PK PRIMARY KEY (AEROPUERTO_ID)
);

-- TABLE: AERONAVE 

CREATE TABLE AERONAVE(
    AERONAVE_ID         NUMBER(10, 0)    NOT NULL,
    MODELO              VARCHAR2(50)     NOT NULL,
    MATRICULA           VARCHAR2(10)     NOT NULL,
    ESPECIFICACIONES    BLOB             NOT NULL,
    ES_COMERICAL        NUMBER(1, 0)     NOT NULL,
    ES_CARGA            NUMBER(1, 0)     NOT NULL,
    CONSTRAINT AERONAVE_PK PRIMARY KEY (AERONAVE_ID),
    CONSTRAINT AERONAVE_TIPO_CHK CHECK( 
        (ES_COMERICAL = 1 AND ES_CARGA = 0 AND SUBSTR(MATRICULA,1,4)='ACOM') OR 
        (ES_COMERICAL = 0 AND ES_CARGA = 1 AND SUBSTR(MATRICULA,1,4)='ACAR') OR 
        (ES_COMERICAL = 1 AND ES_CARGA = 1 AND SUBSTR(MATRICULA,1,4)='ACYC')
    )
);
 
-- TABLE: VUELO 

CREATE TABLE VUELO(
    VUELO_ID              NUMBER(10, 0)    NOT NULL,
    NUM_VUELO             NUMBER(5, 0)     NOT NULL,
    FECHA_SALIDA          TIMESTAMP(6)     NOT NULL,
    FECHA_LLEGADA         TIMESTAMP(6)     NOT NULL,
    SALA                  NUMBER(3, 0),
    FECHA_STATUS          DATE             NOT NULL,
    AEROPUERTO_ORIGEN     NUMBER(10, 0)    NOT NULL,
    AEROPUERTO_DESTINO    NUMBER(10, 0)    NOT NULL,
    STATUS_VUELO_ID       NUMBER(10, 0)    NOT NULL,
    AERONAVE_ID           NUMBER(10, 0)    NOT NULL,
    CONSTRAINT VUELO_PK PRIMARY KEY (VUELO_ID), 
    CONSTRAINT VUELO_AEROPUERTO_ORIGEN_FK FOREIGN KEY (AEROPUERTO_ORIGEN)
    REFERENCES AEROPUERTO(AEROPUERTO_ID),
    CONSTRAINT VUELO_AEROPUERTO_DESTINO_FK FOREIGN KEY (AEROPUERTO_DESTINO)
    REFERENCES AEROPUERTO(AEROPUERTO_ID),
    CONSTRAINT VUELO_STATUS_VUELO_ID_FK FOREIGN KEY (STATUS_VUELO_ID)
    REFERENCES STATUS_VUELO(STATUS_VUELO_ID),
    CONSTRAINT VUELO_AERONAVE_ID_FK FOREIGN KEY (AERONAVE_ID)
    REFERENCES AERONAVE(AERONAVE_ID)
);

-- TABLE: AERONAVE_CARGA 

CREATE TABLE AERONAVE_CARGA(
    AERONAVE_ID                NUMBER(10, 0)    NOT NULL,
    BODEGAS                    NUMBER(5, 0)     NOT NULL,
    CAPACIDAD_CARGA            NUMBER(5, 0)     NOT NULL,
    ALTO                       NUMBER(7, 2)     NOT NULL,
    ANCHO                      NUMBER(7, 2),
    PROFUNDIDAD                NUMBER(7, 2),
    AEROPUERTO_RESGUARDO_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT AERONAVE_CARGA_PK PRIMARY KEY (AERONAVE_ID), 
    CONSTRAINT AERONAVE_CARGA_AERONAVE_ID_FK FOREIGN KEY (AERONAVE_ID)
    REFERENCES AERONAVE(AERONAVE_ID),
    CONSTRAINT AERONAVE_CARGA_AEROPUERTO_RESGUARDO_ID_FK FOREIGN KEY (AEROPUERTO_RESGUARDO_ID)
    REFERENCES AEROPUERTO(AEROPUERTO_ID)
);

-- TABLE: AERONAVE_COMERCIAL 

CREATE TABLE AERONAVE_COMERCIAL(
    AERONAVE_ID                 NUMBER(10, 0)    NOT NULL,
    CAPACIDAD_ORDINARIOS        NUMBER(4, 0)     NOT NULL,
    CAPACIDAD_VIP               NUMBER(4, 0)     NOT NULL,
    CAPACIDAD_DISCAPACITADOS    NUMBER(4, 0)     NOT NULL,
    CONSTRAINT AERONAVE_COMERCIAL_PK PRIMARY KEY (AERONAVE_ID), 
    CONSTRAINT AERONAVE_COMERCIAL_AEROPUERTO_RESGUARDO_ID_FK FOREIGN KEY (AERONAVE_ID)
    REFERENCES AERONAVE(AERONAVE_ID)
);

-- TABLE: EMPLEADO 

CREATE TABLE EMPLEADO(
    EMPLEADO_ID      NUMBER(10, 0)    NOT NULL,
    NOMBRE           VARCHAR2(40)     NOT NULL,
    AP_PAT           VARCHAR2(40)     NOT NULL,
    AP_MAT           VARCHAR2(40),
    RFC              VARCHAR2(13)     NOT NULL,
    CURP             VARCHAR2(18)     NOT NULL,
    FOTO             BLOB             NOT NULL,
    JEFE_EMPLEADO    NUMBER(10, 0),
    PUESTO_ID        NUMBER(10, 0)     NOT NULL,
    CONSTRAINT EMPLEADO_PK PRIMARY KEY (EMPLEADO_ID), 
    CONSTRAINT EMPLEADO_PUESTO_ID_FK FOREIGN KEY (PUESTO_ID)
    REFERENCES PUESTO(PUESTO_ID),
    CONSTRAINT EMPLEADO_JEFE_EMPLEADO_FK FOREIGN KEY (JEFE_EMPLEADO)
    REFERENCES EMPLEADO(EMPLEADO_ID),
    CONSTRAINT EMPLEADO_RFC_UK UNIQUE (RFC),
    CONSTRAINT EMPLEADO_CURP_UK UNIQUE (CURP)
);

-- TABLE: PASAJERO_VUELO 

CREATE TABLE PASAJERO_VUELO(
    PASAJERO_VUELO_ID    NUMBER(10, 0)     NOT NULL,
    ATENCION_ESPECIAL    VARCHAR2(2000),
    PRESENTE             NUMBER(1, 0),
    NUM_ASIENTO          NUMBER(3, 0),
    VUELO_ID             NUMBER(10, 0)     NOT NULL,
    PASAJERO_ID          NUMBER(10, 0)      NOT NULL,
    CONSTRAINT PASAJERO_VUELO_PK PRIMARY KEY (PASAJERO_VUELO_ID), 
    CONSTRAINT PASAJERO_VUELO_VUELO_ID_FK FOREIGN KEY (VUELO_ID)
    REFERENCES VUELO(VUELO_ID),
    CONSTRAINT PASAJERO_VUELO_PASAJERO_ID_FK FOREIGN KEY (PASAJERO_ID)
    REFERENCES PASAJERO(PASAJERO_ID)
);

-- TABLE: EMPLEADO_VUELO 

CREATE TABLE EMPLEADO_VUELO(
    EMPLEADO_ID        NUMBER(10, 0)    NOT NULL,
    VUELO_ID           NUMBER(10, 0)    NOT NULL,
    PUNTUACION         NUMBER(10, 0),
    ROL_EMPLEADO_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT EMPLEADO_VUELO_PK PRIMARY KEY (EMPLEADO_ID, VUELO_ID), 
    CONSTRAINT EMPLEADO_VUELO_EMPLEADO_ID_FK FOREIGN KEY (EMPLEADO_ID)
    REFERENCES EMPLEADO(EMPLEADO_ID),
    CONSTRAINT EMPLEADO_VUELO_VUELO_ID_FK FOREIGN KEY (VUELO_ID)
    REFERENCES VUELO(VUELO_ID),
    CONSTRAINT EMPLEADO_VUELO_ROL_EMPLEADO_ID_FK FOREIGN KEY (ROL_EMPLEADO_ID)
    REFERENCES ROL_EMPLEADO(ROL_EMPLEADO_ID),
    CONSTRAINT EMPLEADO_VUELO_PUNTUACION_CHK CHECK (PUNTUACION IS NULL OR PUNTUACION <= 100)
);

-- TABLE: PASE 

CREATE TABLE PASE(
    PASE_ID              NUMBER(10, 0)    NOT NULL,
    FOLIO_ID             VARCHAR2(8)      NOT NULL,
    FECHA_IMPRESION      TIMESTAMP(6)     NOT NULL,
    PASAJERO_VUELO_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PASE_PK PRIMARY KEY (PASE_ID), 
    CONSTRAINT PASE_PASAJERO_VUELO_ID_FK FOREIGN KEY (PASAJERO_VUELO_ID)
    REFERENCES PASAJERO_VUELO(PASAJERO_VUELO_ID)
);

-- TABLE: EQUIPAJE 

CREATE TABLE EQUIPAJE(
    NUM_EQUIPAJE    NUMBER(10, 0)     NOT NULL,
    PASE_ID         NUMBER(10, 0)    NOT NULL,
    PESO_KG         NUMBER(4, 0),
    CONSTRAINT EQUIPAJE_PK PRIMARY KEY (NUM_EQUIPAJE, PASE_ID), 
    CONSTRAINT EQUIPAJE_PASE_ID_FK FOREIGN KEY (PASE_ID)
    REFERENCES PASE(PASE_ID)
);

-- TABLE: HISTORICO_STATUS_VUELO 

CREATE TABLE HISTORICO_STATUS_VUELO(
    HISTORICO_STATUS_VUELO_ID    NUMBER(10, 0)     NOT NULL,
    FECHA_STATUS                 DATE             NOT NULL,
    VUELO_ID                     NUMBER(10, 0)    NOT NULL,
    STATUS_VUELO_ID              NUMBER(10, 0)    NOT NULL,
    CONSTRAINT HISTORICO_STATUS_VUELO_PK PRIMARY KEY (HISTORICO_STATUS_VUELO_ID), 
    CONSTRAINT HISTORICO_STATUS_VUELO_VUELO_ID_FK FOREIGN KEY (VUELO_ID)
    REFERENCES VUELO(VUELO_ID),
    CONSTRAINT HISTORICO_STATUS_VUELO_STATUS_VUELO_ID_FK FOREIGN KEY (STATUS_VUELO_ID)
    REFERENCES STATUS_VUELO(STATUS_VUELO_ID)
);

-- TABLE: PAQUETE 

CREATE TABLE PAQUETE(
    PAQUETE_ID         NUMBER(10, 0)     NOT NULL,
    FOLIO              VARCHAR2(18)     NOT NULL,
    PESO               NUMBER(7, 0)     NOT NULL,
    TIPO_PAQUETE_ID    NUMBER(10, 0)     NOT NULL,
    VUELO_ID           NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PAQUETE_PK PRIMARY KEY (PAQUETE_ID), 
    CONSTRAINT PAQUETE_TIPO_PAQUETE_ID_FK FOREIGN KEY (TIPO_PAQUETE_ID)
    REFERENCES TIPO_PAQUETE(TIPO_PAQUETE_ID),
    CONSTRAINT PAQUETE_VUELO_ID_FK FOREIGN KEY (VUELO_ID)
    REFERENCES VUELO(VUELO_ID)
);

-- TABLE: UBICACION_MONITOREO 

CREATE TABLE UBICACION_MONITOREO(
    NUM_MEDICION    NUMBER(10, 0)    NOT NULL,
    VUELO_ID        NUMBER(10, 0)    NOT NULL,
    LATITUD         NUMBER(5, 2)     NOT NULL,
    LONGITUD        NUMBER(5, 2)     NOT NULL,
    FECHA_EXACTA    DATE,
    CONSTRAINT UBICACION_MONITOREO_PK PRIMARY KEY (NUM_MEDICION, VUELO_ID), 
    CONSTRAINT UBICACION_MONITOREO_VUELO_ID_FK FOREIGN KEY (VUELO_ID)
    REFERENCES VUELO(VUELO_ID)
);

-- TABLE: WEB_EMPLEADO 

CREATE TABLE WEB_EMPLEADO(
    WEB_EMPLEADO_ID    NUMBER(10, 0)    NOT NULL,
    URL_EMPLEADO       VARCHAR2(300)    NOT NULL,
    EMPLEADO_ID        NUMBER(10, 0)    NOT NULL,
    CONSTRAINT WEB_EMPLEADO_PK PRIMARY KEY (WEB_EMPLEADO_ID), 
    CONSTRAINT WEB_EMPLEADO_EMPLEADO_ID_FK FOREIGN KEY (EMPLEADO_ID)
    REFERENCES EMPLEADO(EMPLEADO_ID)
);



