-- s-05-secuencias.sql
-- @Autor(es): Francisco Hernandez Arturo
--             Toldedo Valencia Jesus Antonio
-- @Fecha creación: 01/06/2024
-- @Descripción: Creación de secuencias para las tablas

-- Secuencia para la tabla AERONAVE
CREATE SEQUENCE SEQ_AERONAVE 
START WITH 1000
INCREMENT BY 1
NOCACHE
NOCYCLE
ORDER;

-- Secuencia para la tabla VUELO
CREATE SEQUENCE SEQ_VUELO 
START WITH 1000
INCREMENT BY 1
NOCACHE
NOCYCLE
ORDER;

-- Secuencia para la tabla PASAJERO
CREATE SEQUENCE SEQ_PASAJERO 
START WITH 1000
INCREMENT BY 1
NOCACHE
NOCYCLE
ORDER;

-- Secuencia para la tabla AEROPUERTO
CREATE SEQUENCE SEQ_AEROPUERTO 
START WITH 1000
INCREMENT BY 1
NOCACHE
NOCYCLE
ORDER;

-- Secuencia para la tabla EMPLEADO
CREATE SEQUENCE SEQ_EMPLEADO 
START WITH 1000
INCREMENT BY 1
NOCACHE
NOCYCLE
ORDER;

-- Secuencia para la tabla PASAJERO_VUELO
CREATE SEQUENCE SEQ_PASAJERO_VUELO 
START WITH 1000
INCREMENT BY 1
NOCACHE
NOCYCLE
ORDER;

-- Secuencia para la tabla PASE
CREATE SEQUENCE SEQ_PASE 
START WITH 1000
INCREMENT BY 1
NOCACHE
NOCYCLE
ORDER;

-- Secuencia para la tabla EQUIPAJE
CREATE SEQUENCE SEQ_EQUIPAJE 
START WITH 1000
INCREMENT BY 1
NOCACHE
NOCYCLE
ORDER;

-- Secuencia para la tabla HISTORICO_STATUS_VUELO
CREATE SEQUENCE SEQ_HISTORICO_STATUS_VUELO 
START WITH 1000
INCREMENT BY 1
NOCACHE
NOCYCLE
ORDER;

-- Secuencia para la tabla PAQUETE
CREATE SEQUENCE SEQ_PAQUETE 
START WITH 1000
INCREMENT BY 1
NOCACHE
NOCYCLE
ORDER;

-- Secuencia para la tabla WEB_EMPLEADO
CREATE SEQUENCE SEQ_WEB_EMPLEADO 
START WITH 1000
INCREMENT BY 1
NOCACHE
NOCYCLE
ORDER;

COMMIT;
